// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'collectionitem-search'
  | 'error-connector-toomany'
  | 'error-noItemSelected'
  | 'item-section-example1-head-text'
  | 'item-section-example1-sidenav-tooltip'
  | 'item-section-example2-button-tooltip'
  | 'item-section-example2-head-text'
  | 'item-section-example2-sidenav-tooltip'
  | 'menuitem-connector'
  | 'menuitem-main'
  | 'menuitem-search'
  | 'pref-enable'
  | 'pref-help'
  | 'pref-input'
  | 'pref-title';
