// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'collectionitem-search'
  | 'error-connector-toomany'
  | 'error-noItemSelected'
  | 'menuitem-connector'
  | 'menuitem-main'
  | 'menuitem-search';
